//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAws.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZAws.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mkdir /var/rails_apps/{0}
        ///cd /var/rails_apps/{0}
        ///git init
        ///git remote add origin {1}
        ///git pull origin master
        ///
        ///bundle install
        ///
        ///service mysqld start
        ///rake db:create RAILS_ENV=&quot;production&quot;
        ///rake db:migrate RAILS_ENV=&quot;production&quot;
        ///rake assets:precompile
        ///
        ///
        ///chmod 777 /var/rails_apps/{0} -R
        ///
        ///echo &quot;&lt;VirtualHost *:80&gt;
        ///    ServerName {2}
        ///    DocumentRoot /var/rails_apps/{0}{3}
        ///    &lt;Directory /var/rails_apps/{0}{3}&gt;
        ///       AllowOverride all
        ///       Options -MultiViews
        ///    &lt;/Directory&gt;
        ///&lt;/VirtualHost&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddAppScript {
            get {
                return ResourceManager.GetString("AddAppScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to echo &quot;&lt;VirtualHost *:80&gt;
        ///    ServerName {1}
        ///    DocumentRoot /var/rails_apps/{0}{2}
        ///    &lt;Directory /var/rails_apps/{0}{2}&gt;
        ///       AllowOverride all
        ///       Options -MultiViews
        ///    &lt;/Directory&gt;
        ///&lt;/VirtualHost&gt;
        ///&quot; &gt; /etc/httpd/virtual_hosts/{3}{0}.conf.
        /// </summary>
        internal static string ConfigText {
            get {
                return ResourceManager.GetString("ConfigText", resourceCulture);
            }
        }
    }
}
